name: movie_time
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  http: ^1.2.0
  intl: ^0.19.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  dart_style: 2.3.4 # Workaround https://github.com/dart-lang/dart_style/issues/1413
  json_serializable: ^6.7.1
  flutter_launcher_icons: "^0.9.2"


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
  fonts:
    - family: Title_logo
      fonts:
        - asset: fonts/Bahianita-Regular.ttf

